-- AlterTable
ALTER TABLE "Package" ADD COLUMN     "bannerUrl" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "homepage" DROP NOT NULL,
ALTER COLUMN "license" DROP NOT NULL,
ALTER COLUMN "licenseUrl" DROP NOT NULL,
ALTER COLUMN "featured" SET DEFAULT false;
